name = "pfpk"
main = "src/index.ts"
compatibility_date = "2022-10-04"
node_compat = true

routes = [
  { pattern = "pfpk.daodao.zone", custom_domain = true, zone_name = "daodao.zone" }
]

kv_namespaces = [
  { binding = "PROFILES", id = "11f7f932cab14af0a5a382c7bea3c9d6", preview_id = "eb64b733815a4bf580bcbfcacfbb7ab5" }
]
